driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: centos-6
  - name: centos-7
  - name: debian-7
  - name: debian-8
  - name: debian-9
  - name: fedora-26
  - name: opensuse-leap-42
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[test::default]
  - name: instance
    run_list:
      - recipe[test::instance]
  - name: runit_instance
    run_list:
      - recipe[test::runit]
    excludes:
      - opensuse-leap-42
